# Generated by Django 5.1.4 on 2025-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('due_data', models.DateTimeField(blank=True, null=True, verbose_name='Сроки выполненения')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
